os: linux
dist: xenial
language: python
cache: pip

python:
   - "3.7"

# services:
#   - mysql

# env:
#   -DJANGO=1.8 DB=mysql

install:
   - pip install -r requirements.txt
   
# before_script:
#       - mysql -e 'create database test;' -u root

script:
   - python -V 
#     - python manage.py test
